// Code generated by "stringer -type=ResponseCode"; DO NOT EDIT.

package model

import "fmt"

const _ResponseCode_name = "OKFail"

var _ResponseCode_index = [...]uint8{0, 2, 6}

func (i ResponseCode) String() string {
	i -= 1
	if i < 0 || i >= ResponseCode(len(_ResponseCode_index)-1) {
		return fmt.Sprintf("ResponseCode(%d)", i+1)
	}
	return _ResponseCode_name[_ResponseCode_index[i]:_ResponseCode_index[i+1]]
}
