// automatically generated by the FlatBuffers compiler, do not modify

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AccountCreate struct {
	_tab flatbuffers.Table
}

func GetRootAsAccountCreate(buf []byte, offset flatbuffers.UOffsetT) *AccountCreate {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AccountCreate{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *AccountCreate) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AccountCreate) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AccountCreate) Username() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AccountCreate) Signatories(obj *Signature, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *AccountCreate) SignatoriesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *AccountCreate) Quorum() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AccountCreate) MutateQuorum(n byte) bool {
	return rcv._tab.MutateByteSlot(8, n)
}

func (rcv *AccountCreate) TargetDomain() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func AccountCreateStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func AccountCreateAddUsername(builder *flatbuffers.Builder, username flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(username), 0)
}
func AccountCreateAddSignatories(builder *flatbuffers.Builder, signatories flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(signatories), 0)
}
func AccountCreateStartSignatoriesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func AccountCreateAddQuorum(builder *flatbuffers.Builder, quorum byte) {
	builder.PrependByteSlot(2, quorum, 0)
}
func AccountCreateAddTargetDomain(builder *flatbuffers.Builder, targetDomain flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(targetDomain), 0)
}
func AccountCreateEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
