// automatically generated by the FlatBuffers compiler, do not modify

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AccountDelete struct {
	_tab flatbuffers.Table
}

func GetRootAsAccountDelete(buf []byte, offset flatbuffers.UOffsetT) *AccountDelete {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AccountDelete{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *AccountDelete) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AccountDelete) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AccountDelete) TargetAccount() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func AccountDeleteStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func AccountDeleteAddTargetAccount(builder *flatbuffers.Builder, targetAccount flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(targetAccount), 0)
}
func AccountDeleteEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
