// automatically generated by the FlatBuffers compiler, do not modify

package protocol

const (
	AccountActionNONE = 0
	AccountActionSignatoriesRegister = 1
	AccountActionSignatoriesUnregister = 2
	AccountActionAccountSetQuorum = 3
	AccountActionAccountDelegate = 4
	AccountActionAccountUndelegate = 5
)

var EnumNamesAccountAction = map[int]string{
	AccountActionNONE:"NONE",
	AccountActionSignatoriesRegister:"SignatoriesRegister",
	AccountActionSignatoriesUnregister:"SignatoriesUnregister",
	AccountActionAccountSetQuorum:"AccountSetQuorum",
	AccountActionAccountDelegate:"AccountDelegate",
	AccountActionAccountUndelegate:"AccountUndelegate",
}

