// automatically generated by the FlatBuffers compiler, do not modify

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AccountUnregister struct {
	_tab flatbuffers.Table
}

func GetRootAsAccountUnregister(buf []byte, offset flatbuffers.UOffsetT) *AccountUnregister {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AccountUnregister{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *AccountUnregister) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AccountUnregister) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AccountUnregister) TargetAccount() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AccountUnregister) TargetDomain() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func AccountUnregisterStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func AccountUnregisterAddTargetAccount(builder *flatbuffers.Builder, targetAccount flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(targetAccount), 0)
}
func AccountUnregisterAddTargetDomain(builder *flatbuffers.Builder, targetDomain flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(targetDomain), 0)
}
func AccountUnregisterEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
