// automatically generated by the FlatBuffers compiler, do not modify

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AccountDelegate struct {
	_tab flatbuffers.Table
}

func GetRootAsAccountDelegate(buf []byte, offset flatbuffers.UOffsetT) *AccountDelegate {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AccountDelegate{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *AccountDelegate) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AccountDelegate) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AccountDelegate) AuditorAccount() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func AccountDelegateStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func AccountDelegateAddAuditorAccount(builder *flatbuffers.Builder, auditorAccount flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(auditorAccount), 0)
}
func AccountDelegateEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
