// automatically generated by the FlatBuffers compiler, do not modify

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AccountSetQuorum struct {
	_tab flatbuffers.Table
}

func GetRootAsAccountSetQuorum(buf []byte, offset flatbuffers.UOffsetT) *AccountSetQuorum {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AccountSetQuorum{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *AccountSetQuorum) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AccountSetQuorum) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AccountSetQuorum) TargetAccount() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AccountSetQuorum) Quorum() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AccountSetQuorum) MutateQuorum(n byte) bool {
	return rcv._tab.MutateByteSlot(6, n)
}

func AccountSetQuorumStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func AccountSetQuorumAddTargetAccount(builder *flatbuffers.Builder, targetAccount flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(targetAccount), 0)
}
func AccountSetQuorumAddQuorum(builder *flatbuffers.Builder, quorum byte) {
	builder.PrependByteSlot(1, quorum, 0)
}
func AccountSetQuorumEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
