// automatically generated by the FlatBuffers compiler, do not modify

package protocol

const (
	ActionNONE = 0
	ActionAssetActionWrapper = 1
	ActionAccountActionWrapper = 2
	ActionDomainActionWrapper = 3
	ActionPeerActionWrapper = 4
)

var EnumNamesAction = map[int]string{
	ActionNONE:"NONE",
	ActionAssetActionWrapper:"AssetActionWrapper",
	ActionAccountActionWrapper:"AccountActionWrapper",
	ActionDomainActionWrapper:"DomainActionWrapper",
	ActionPeerActionWrapper:"PeerActionWrapper",
}

