// automatically generated by the FlatBuffers compiler, do not modify

package protocol

const (
	AnyAssetNONE = 0
	AnyAssetCurrency = 1
	AnyAssetComplexAsset = 2
)

var EnumNamesAnyAsset = map[int]string{
	AnyAssetNONE:"NONE",
	AnyAssetCurrency:"Currency",
	AnyAssetComplexAsset:"ComplexAsset",
}

