// automatically generated by the FlatBuffers compiler, do not modify

package protocol

const (
	AssetActionNONE = 0
	AssetActionAdd = 1
	AssetActionSubtract = 2
	AssetActionTransfer = 3
	AssetActionExchange = 4
	AssetActionAssetSetPermission = 5
)

var EnumNamesAssetAction = map[int]string{
	AssetActionNONE:"NONE",
	AssetActionAdd:"Add",
	AssetActionSubtract:"Subtract",
	AssetActionTransfer:"Transfer",
	AssetActionExchange:"Exchange",
	AssetActionAssetSetPermission:"AssetSetPermission",
}

