// automatically generated by the FlatBuffers compiler, do not modify

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AssetDelete struct {
	_tab flatbuffers.Table
}

func GetRootAsAssetDelete(buf []byte, offset flatbuffers.UOffsetT) *AssetDelete {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AssetDelete{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *AssetDelete) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AssetDelete) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AssetDelete) TargetAsset() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func AssetDeleteStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func AssetDeleteAddTargetAsset(builder *flatbuffers.Builder, targetAsset flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(targetAsset), 0)
}
func AssetDeleteEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
