// automatically generated by the FlatBuffers compiler, do not modify

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AssetMove struct {
	_tab flatbuffers.Table
}

func GetRootAsAssetMove(buf []byte, offset flatbuffers.UOffsetT) *AssetMove {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AssetMove{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *AssetMove) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AssetMove) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AssetMove) TargetAsset() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AssetMove) DestinationDomain() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func AssetMoveStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func AssetMoveAddTargetAsset(builder *flatbuffers.Builder, targetAsset flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(targetAsset), 0)
}
func AssetMoveAddDestinationDomain(builder *flatbuffers.Builder, destinationDomain flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(destinationDomain), 0)
}
func AssetMoveEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
