// automatically generated by the FlatBuffers compiler, do not modify

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AssetCreate struct {
	_tab flatbuffers.Table
}

func GetRootAsAssetCreate(buf []byte, offset flatbuffers.UOffsetT) *AssetCreate {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AssetCreate{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *AssetCreate) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AssetCreate) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AssetCreate) Asset(obj *Asset) *Asset {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Asset)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func AssetCreateStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func AssetCreateAddAsset(builder *flatbuffers.Builder, asset flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(asset), 0)
}
func AssetCreateEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
