// automatically generated by the FlatBuffers compiler, do not modify

package protocol

const (
	BlockStateUNCOMMITTED = 0
	BlockStateCOMMITTED = 1
)

var EnumNamesBlockState = map[int]string{
	BlockStateUNCOMMITTED:"UNCOMMITTED",
	BlockStateCOMMITTED:"COMMITTED",
}

