// automatically generated by the FlatBuffers compiler, do not modify

package protocol

const (
	BlockStateCOMMITTED = 0
	BlockStateUNCOMMITTED = 1
)

var EnumNamesBlockState = map[int]string{
	BlockStateCOMMITTED:"COMMITTED",
	BlockStateUNCOMMITTED:"UNCOMMITTED",
}

