// automatically generated by the FlatBuffers compiler, do not modify

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ComplexAsset struct {
	_tab flatbuffers.Table
}

func GetRootAsComplexAsset(buf []byte, offset flatbuffers.UOffsetT) *ComplexAsset {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ComplexAsset{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ComplexAsset) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ComplexAsset) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ComplexAsset) Prop(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *ComplexAsset) PropLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ComplexAsset) PropBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ComplexAssetStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ComplexAssetAddProp(builder *flatbuffers.Builder, prop flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(prop), 0)
}
func ComplexAssetStartPropVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func ComplexAssetEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
