// automatically generated by the FlatBuffers compiler, do not modify

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Currency struct {
	_tab flatbuffers.Table
}

func GetRootAsCurrency(buf []byte, offset flatbuffers.UOffsetT) *Currency {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Currency{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Currency) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Currency) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Currency) Amount(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *Currency) AmountLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *Currency) AmountBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Currency) Precision() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Currency) MutatePrecision(n byte) bool {
	return rcv._tab.MutateByteSlot(6, n)
}

func CurrencyStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func CurrencyAddAmount(builder *flatbuffers.Builder, amount flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(amount), 0)
}
func CurrencyStartAmountVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func CurrencyAddPrecision(builder *flatbuffers.Builder, precision byte) {
	builder.PrependByteSlot(1, precision, 0)
}
func CurrencyEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
