// automatically generated by the FlatBuffers compiler, do not modify

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Delete struct {
	_tab flatbuffers.Table
}

func GetRootAsDelete(buf []byte, offset flatbuffers.UOffsetT) *Delete {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Delete{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Delete) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Delete) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Delete) Target() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func DeleteStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func DeleteAddTarget(builder *flatbuffers.Builder, target flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(target), 0)
}
func DeleteEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
