// automatically generated by the FlatBuffers compiler, do not modify

package protocol

const (
	DomainActionNONE = 0
	DomainActionAssetCreate = 1
	DomainActionDomainCreate = 2
	DomainActionDelete = 3
	DomainActionMove = 4
	DomainActionAccountDelete = 5
	DomainActionAccountRegister = 6
	DomainActionAccountUnregister = 7
	DomainActionDomainSetPermission = 8
	DomainActionDomainSetNotify = 9
)

var EnumNamesDomainAction = map[int]string{
	DomainActionNONE:"NONE",
	DomainActionAssetCreate:"AssetCreate",
	DomainActionDomainCreate:"DomainCreate",
	DomainActionDelete:"Delete",
	DomainActionMove:"Move",
	DomainActionAccountDelete:"AccountDelete",
	DomainActionAccountRegister:"AccountRegister",
	DomainActionAccountUnregister:"AccountUnregister",
	DomainActionDomainSetPermission:"DomainSetPermission",
	DomainActionDomainSetNotify:"DomainSetNotify",
}

