// automatically generated by the FlatBuffers compiler, do not modify

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DomainMove struct {
	_tab flatbuffers.Table
}

func GetRootAsDomainMove(buf []byte, offset flatbuffers.UOffsetT) *DomainMove {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DomainMove{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *DomainMove) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DomainMove) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DomainMove) SourceDomain() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DomainMove) DestinationDomian() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func DomainMoveStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func DomainMoveAddSourceDomain(builder *flatbuffers.Builder, sourceDomain flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(sourceDomain), 0)
}
func DomainMoveAddDestinationDomian(builder *flatbuffers.Builder, destinationDomian flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(destinationDomian), 0)
}
func DomainMoveEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
