// automatically generated by the FlatBuffers compiler, do not modify

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PeerAdd struct {
	_tab flatbuffers.Table
}

func GetRootAsPeerAdd(buf []byte, offset flatbuffers.UOffsetT) *PeerAdd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PeerAdd{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *PeerAdd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PeerAdd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PeerAdd) Peer(obj *Peer) *Peer {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Peer)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func PeerAddStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func PeerAddAddPeer(builder *flatbuffers.Builder, peer flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(peer), 0)
}
func PeerAddEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
