// automatically generated by the FlatBuffers compiler, do not modify

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PeerActionWrapper struct {
	_tab flatbuffers.Table
}

func GetRootAsPeerActionWrapper(buf []byte, offset flatbuffers.UOffsetT) *PeerActionWrapper {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PeerActionWrapper{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *PeerActionWrapper) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PeerActionWrapper) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PeerActionWrapper) ActionType() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PeerActionWrapper) MutateActionType(n byte) bool {
	return rcv._tab.MutateByteSlot(4, n)
}

func (rcv *PeerActionWrapper) Action(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func PeerActionWrapperStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func PeerActionWrapperAddActionType(builder *flatbuffers.Builder, actionType byte) {
	builder.PrependByteSlot(0, actionType, 0)
}
func PeerActionWrapperAddAction(builder *flatbuffers.Builder, action flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(action), 0)
}
func PeerActionWrapperEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
