// automatically generated by the FlatBuffers compiler, do not modify

package protocol

const (
	PeerActionNONE = 0
	PeerActionPeerAdd = 1
	PeerActionPeerRemove = 2
	PeerActionPeerSetTrust = 3
	PeerActionPeerChangeTrust = 4
	PeerActionPeerSetState = 5
)

var EnumNamesPeerAction = map[int]string{
	PeerActionNONE:"NONE",
	PeerActionPeerAdd:"PeerAdd",
	PeerActionPeerRemove:"PeerRemove",
	PeerActionPeerSetTrust:"PeerSetTrust",
	PeerActionPeerChangeTrust:"PeerChangeTrust",
	PeerActionPeerSetState:"PeerSetState",
}

