// automatically generated by the FlatBuffers compiler, do not modify

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PeerSetState struct {
	_tab flatbuffers.Table
}

func GetRootAsPeerSetState(buf []byte, offset flatbuffers.UOffsetT) *PeerSetState {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PeerSetState{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *PeerSetState) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PeerSetState) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PeerSetState) TargetPeer() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PeerSetState) State() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PeerSetState) MutateState(n byte) bool {
	return rcv._tab.MutateByteSlot(6, n)
}

func PeerSetStateStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func PeerSetStateAddTargetPeer(builder *flatbuffers.Builder, targetPeer flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(targetPeer), 0)
}
func PeerSetStateAddState(builder *flatbuffers.Builder, state byte) {
	builder.PrependByteSlot(1, state, 0)
}
func PeerSetStateEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
