// automatically generated by the FlatBuffers compiler, do not modify

package protocol

const (
	ResponseCodeOK = 0
	ResponseCodeFAIL = 1
)

var EnumNamesResponseCode = map[int]string{
	ResponseCodeOK:"OK",
	ResponseCodeFAIL:"FAIL",
}

