// automatically generated by the FlatBuffers compiler, do not modify

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SignatoriesUnregister struct {
	_tab flatbuffers.Table
}

func GetRootAsSignatoriesUnregister(buf []byte, offset flatbuffers.UOffsetT) *SignatoriesUnregister {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SignatoriesUnregister{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *SignatoriesUnregister) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SignatoriesUnregister) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SignatoriesUnregister) FromAccount() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SignatoriesUnregister) Signatories(obj *Signature, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *SignatoriesUnregister) SignatoriesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func SignatoriesUnregisterStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func SignatoriesUnregisterAddFromAccount(builder *flatbuffers.Builder, fromAccount flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(fromAccount), 0)
}
func SignatoriesUnregisterAddSignatories(builder *flatbuffers.Builder, signatories flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(signatories), 0)
}
func SignatoriesUnregisterStartSignatoriesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func SignatoriesUnregisterEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
