// automatically generated by the FlatBuffers compiler, do not modify

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SignatoriesRegister struct {
	_tab flatbuffers.Table
}

func GetRootAsSignatoriesRegister(buf []byte, offset flatbuffers.UOffsetT) *SignatoriesRegister {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SignatoriesRegister{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *SignatoriesRegister) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SignatoriesRegister) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SignatoriesRegister) ToAccount() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SignatoriesRegister) Signatories(obj *Signature, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *SignatoriesRegister) SignatoriesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func SignatoriesRegisterStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func SignatoriesRegisterAddToAccount(builder *flatbuffers.Builder, toAccount flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(toAccount), 0)
}
func SignatoriesRegisterAddSignatories(builder *flatbuffers.Builder, signatories flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(signatories), 0)
}
func SignatoriesRegisterStartSignatoriesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func SignatoriesRegisterEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
