// automatically generated by the FlatBuffers compiler, do not modify

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SignatureWithState struct {
	_tab flatbuffers.Table
}

func GetRootAsSignatureWithState(buf []byte, offset flatbuffers.UOffsetT) *SignatureWithState {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SignatureWithState{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *SignatureWithState) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SignatureWithState) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SignatureWithState) Signature(obj *Signature) *Signature {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Signature)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *SignatureWithState) State() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SignatureWithState) MutateState(n byte) bool {
	return rcv._tab.MutateByteSlot(6, n)
}

func SignatureWithStateStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func SignatureWithStateAddSignature(builder *flatbuffers.Builder, signature flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(signature), 0)
}
func SignatureWithStateAddState(builder *flatbuffers.Builder, state byte) {
	builder.PrependByteSlot(1, state, 0)
}
func SignatureWithStateEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
