// automatically generated by the FlatBuffers compiler, do not modify

package protocol

const (
	StatusReject = 0
	StatusApprove = 1
	StatusPending = 2
)

var EnumNamesStatus = map[int]string{
	StatusReject:"Reject",
	StatusApprove:"Approve",
	StatusPending:"Pending",
}

