// automatically generated by the FlatBuffers compiler, do not modify

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Subtract struct {
	_tab flatbuffers.Table
}

func GetRootAsSubtract(buf []byte, offset flatbuffers.UOffsetT) *Subtract {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Subtract{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Subtract) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Subtract) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Subtract) TargetAccount() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Subtract) Asset(obj *Asset) *Asset {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Asset)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func SubtractStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func SubtractAddTargetAccount(builder *flatbuffers.Builder, targetAccount flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(targetAccount), 0)
}
func SubtractAddAsset(builder *flatbuffers.Builder, asset flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(asset), 0)
}
func SubtractEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
