// automatically generated by the FlatBuffers compiler, do not modify

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Transfer struct {
	_tab flatbuffers.Table
}

func GetRootAsTransfer(buf []byte, offset flatbuffers.UOffsetT) *Transfer {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Transfer{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Transfer) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Transfer) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Transfer) SenderAccount() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Transfer) ReceiverAccount() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Transfer) Asset(obj *Asset) *Asset {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Asset)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func TransferStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func TransferAddSenderAccount(builder *flatbuffers.Builder, senderAccount flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(senderAccount), 0)
}
func TransferAddReceiverAccount(builder *flatbuffers.Builder, receiverAccount flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(receiverAccount), 0)
}
func TransferAddAsset(builder *flatbuffers.Builder, asset flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(asset), 0)
}
func TransferEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
